# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'photos' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for photos
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'photos-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-maps', :path => '../node_modules/react-native-maps'

    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  end

  target 'photosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'photos-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for photos-tvOS

  target 'photos-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
